server:
  port: 8888

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test

  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: billing-service
              uri: lb://BILLING-SERVICE
              predicates:
                - Path=/billing-service/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-service/**
            - id: shipping-service
              uri: lb://SHIPPING-SERVICE
              predicates:
                - Path=/shipping-service/**
            - id: product-service-swagger
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/v3/api-docs
            - id: user-service-swagger
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/v3/api-docs
            - id: shipping-service-swagger
              uri: lb://SHIPPING-SERVICE
              predicates:
                - Path=/shipping/v3/api-docs
            - id: order-service-swagger
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/v3/api-docs
            - id: billing-service-swagger
              uri: lb://BILLING-SERVICE
              predicates:
                - Path=/billings/v3/api-docs
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:4200"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - Accept
                  - Origin
                  - X-Requested-With
                allow-credentials: true
                max-age: 3600

springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: user-service
        url: /user/v3/api-docs
      - name: product-service
        url: /products/v3/api-docs
      - name: shipping-service
        url: /shipping/v3/api-docs
      - name: order-service
        url: /orders/v3/api-docs
      - name: billing-service
        url: /billings/v3/api-docs

  api-docs:
    path: /v3/api-docs
  show-actuator: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    reactor.netty: WARN
    io.netty: WARN
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: WARN
    org.springframework.web.reactive: WARN
    tn.epac.Gateway_service.Config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/app.log   # Chemin relatif au dossier racine de ton projet

app:
  swagger:
    gateway-mode: true